module.exports = [
  { name: "România", code: "RO" },
  { name: "Belgia", code: "BE" },
  { name: "Austria", code: "AT" },
  { name: "Bulgaria", code: "BG" },
  { name: "Cipru", code: "CY" },
  { name: "Croația", code: "HR" },
  { name: "Danemarca", code: "DK" },
  { name: "Estonia", code: "EE" },
  { name: "Finlanda", code: "FI" },
  { name: "Franța", code: "FR" },
  { name: "Germania", code: "DE" },
  { name: "Grecia", code: "EL" },
  { name: "Irlanda", code: "IE" },
  { name: "Afganistan", code: "AF" },
  { name: "Africa de Sud", code: "ZA" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Antigua și Barbuda", code: "AG" },
  { name: "Arabia Saudită", code: "SA" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Azerbaidjan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bhutan", code: "BT" },
  { name: "Birmania", code: "MM" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia și Herțegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Brazilia", code: "BR" },
  { name: "Brunei", code: "BN" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodgia", code: "KH" },
  { name: "Camerun", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Capul Verde", code: "CV" },
  { name: "Cehia", code: "CZ" },
  { name: "Republica Centrafricană", code: "FC" },
  { name: "Chile", code: "CL" },
  { name: "Republica Populară Chineză", code: "CN" },
  { name: "Ciad", code: "TD" },
  { name: "Coasta de Fildeș", code: "CI" },
  { name: "Columbia", code: "CO" },
  { name: "Comore", code: "KM" },
  { name: "Republica Democrată Congo", code: "CD" },
  { name: "Republica Congo", code: "CG" },
  { name: "Coreea de Nord", code: "KP" },
  { name: "Coreea de Sud", code: "KR" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cuba", code: "CU" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Republica Dominicană", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egipt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Elveția", code: "CH" },
  { name: "Emiratele Arabe Unite", code: "AE" },
  { name: "Eritreea", code: "ER" },
  { name: "Etiopia", code: "ET" },
  { name: "Fiji", code: "FJ" },
  { name: "Filipine", code: "PH" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Ghana", code: "GH" },
  { name: "Grenada", code: "GD" },
  { name: "Guineea", code: "GN" },
  { name: "Guineea-Bissau", code: "GW" },
  { name: "Guineea Ecuatorială", code: "GQ" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Honduras", code: "HN" },
  { name: "India", code: "IN" },
  { name: "Indonezia", code: "ID" },
  { name: "Iordania", code: "JO" },
  { name: "Iran", code: "IR" },
  { name: "Islanda", code: "IS" },
  { name: "Israel", code: "IL" },
  { name: "Italia", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japonia", code: "JP" },
  { name: "Kazahstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kârgâzstan", code: "KG" },
  { name: "Kiribati", code: "KI" },
  { name: "Kuweit", code: "KW" },
  { name: "Laos", code: "LA" },
  { name: "Lesotho", code: "LS" },
  { name: "Letonia", code: "LV" },
  { name: "Liban", code: "LB" },
  { name: "Liberia", code: "LR" },
  { name: "Libia", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lituania", code: "LT" },
  { name: "Luxemburg", code: "LU" },
  { name: "Republica Macedonia", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaezia", code: "MY" },
  { name: "Maldive", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Maroc", code: "MA" },
  { name: "Insulele Marshall", code: "MH" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mexic", code: "MX" },
  { name: "Statele Federate ale Microneziei", code: "FM" },
  { name: "Republica Moldova", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Mozambic", code: "MZ" },
  { name: "Muntenegru", code: "XM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Norvegia", code: "NO" },
  { name: "Noua Zeelandă", code: "NZ" },
  { name: "Olanda", code: "NL" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestina", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua Noua Guinee", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Polonia", code: "PL" },
  { name: "Portugalia", code: "PT" },
  { name: "Qatar", code: "QA" },
  { name: "Regatul Unit", code: "GB" },
  { name: "Rusia", code: "RU" },
  { name: "Rwanda", code: "RW" },
  { name: "Samoa", code: "AS" },
  { name: "San Marino", code: "SM" },
  { name: "São Tomé și Príncipe", code: "ST" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "XS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sfântul Cristofor și Nevis", code: "KN" },
  { name: "Sfânta Lucia", code: "LC" },
  { name: "Sfântul Vicențiu și Grenadinele", code: "VC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Siria", code: "SY" },
  { name: "Slovacia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Insulele Solomon", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "Spania", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Statele Unite ale Americii", code: "UA" },
  { name: "Sudan", code: "SD" },
  { name: "Sudanul de Sud", code: "SS" },
  { name: "Suedia", code: "SE" },
  { name: "Surinam", code: "SR" },
  { name: "Swaziland", code: "SZ" },
  { name: "Tadjikistan", code: "TJ" },
  { name: "Tanzania", code: "TZ" },
  { name: "Thailanda", code: "TH" },
  { name: "Timorul de Est", code: "TP" },
  { name: "Togo", code: "TG" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad-Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turcia", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Tuvalu", code: "TV" },
  { name: "Ucraina", code: "UA" },
  { name: "Uganda", code: "UG" },
  { name: "Ungaria", code: "HU" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Vatican", code: "VA" },
  { name: "Venezuela", code: "VE" },
  { name: "Vietnam", code: "VN" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];