module.exports = [
  { name: 'Alpha Bank', short_name: 'AB' },
  { name: 'BRCI', short_name: 'BRCI' },
  { name: 'Banca FEROVIARA', short_name: 'BF' },
  { name: 'Intesa Sanpaolo', short_name: 'IS' },
  { name: 'BCR', short_name: 'BCR' },
  { name: 'BCR Banca pentru Locuinţe', short_name: 'BCRL' },
  { name: 'Eximbank', short_name: 'EX' },
  { name: 'Banca Românească', short_name: 'BR' },
  { name: 'Banca Transilvania', short_name: 'BT' },
  { name: 'Leumi', short_name: 'LM' },
  { name: 'BRD', short_name: 'BRD' },
  { name: 'CEC Bank', short_name: 'CEC' },
  { name: 'Credit Agricole', short_name: 'CA' },
  { name: 'Credit Europe', short_name: 'CE' },
  { name: 'Garanti Bank', short_name: 'GB' },
  { name: 'Idea Bank', short_name: 'IB' },
  { name: 'Libra Bank', short_name: 'LB' },
  { name: 'Vista Bank', short_name: 'VB' },
  { name: 'OTP Bank', short_name: 'OTP' },
  { name: 'Patria Bank', short_name: 'PB' },
  { name: 'First Bank', short_name: 'FB' },
  { name: 'Porsche Bank', short_name: 'POB' },
  { name: 'ProCredit Bank', short_name: 'PROB' },
  { name: 'Raiffeisen Bank', short_name: 'RB' },
  { name: 'Aedificium Banca pentru Locuinte', short_name: 'ADB' },
  { name: 'UniCredit Bank', short_name: 'UB' },
  { name: 'Alior Bank', short_name: 'ALB' },
  { name: 'BLOM Bank France', short_name: 'BLB' },
  { name: 'BNP Paribas', short_name: 'BNP' },
  { name: 'Citibank', short_name: 'CB' },
  { name: 'ING', short_name: 'ING' },
  { name: 'TBI Bank', short_name: 'TBIB' },
  { name: 'Alta banca', short_name: null }
];
