default:
    port  : #{process.env.PORT}
    env   : #{process.env.NODE_ENV}
    sKey  : #{process.env.ENCRYPTION_SECRET_KEY}
    dbSsl : #{process.env.DB_SSL}
    poolMax : #{process.env.POOL_MAX}

    AWS_REGION : #{process.env.AWS_REGION}
    AWS_ACCESS_KEY_ID : #{process.env.AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY : #{process.env.AWS_SECRET_ACCESS_KEY}